build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test:
  image: cypress/base
  stage: test
  script:
    - npm ci
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/screenshots/**/*.png
      - cypress/videos/**/*.mp4
    expire_in: 1 day